WIP - DO NOT MERGE - DCOS CLI Integration
typesafehub/conductr-cli pull request #172
Opened 2016-10-26 09:00 UTC by huntc

This commit provides the changes required in order for the "conduct" CLI to be integrated with the DC/OS CLI such that you can "dcos conduct ..." and the ConductR commands are channelled via DC/OS's admin gateway.

* [ ] Tests required for dcos_mode oriented code
* [ ] `dcos conduct load` isn't working because of the behaviour of the DC/OS CLI ([reported as an issue](https://github.com/dcos/dcos-cli/issues/818))

2016-10-26 09:04 UTC, huntc commented
Observational testing:

```
ChristohersMBP2:conductr-cli huntc$ dcos 
Command line utility for the Mesosphere Datacenter Operating
System (DC/OS). The Mesosphere DC/OS is a distributed operating
system built around Apache Mesos. This utility provides tools
for easy management of a DC/OS installation.

Available DC/OS commands:

	auth           	Authenticate to DC/OS cluster
	conduct        	Lightbend ConductR sub commands. Type 'dcos conduct' to see more.
	config         	Manage the DC/OS configuration file
	help           	Display help information about DC/OS
	marathon       	Deploy and manage applications to DC/OS
	node           	Administer and manage DC/OS cluster nodes
	package        	Install and manage DC/OS software packages
	service        	Manage DC/OS services
	task           	Manage DC/OS tasks

Get detailed command description with 'dcos <command> --help'.
ChristohersMBP2:conductr-cli huntc$ 
ChristohersMBP2:conductr-cli huntc$ 
ChristohersMBP2:conductr-cli huntc$ dcos conduct info
ID       NAME        #REP  #STR  #RUN
c14bd62  visualizer     1     0     0
```

2016-10-26 09:27 UTC, huntc commented
Failing because of the DC/OS Python library unable to be found.

2016-10-26 11:55 UTC, viktorklang commented on conductr_cli/conduct_main.py
> +                            help='The optional ConductR scheme, defaults to `http`',
Shouldn't something as important as the orchestrator API default to https? (perhaps that's for the future?)

2016-10-26 19:35 UTC, huntc commented on conductr_cli/conduct_main.py
> +                            help='The optional ConductR scheme, defaults to `http`',
Agreed. TLS support for the control protocol is planned. Meanwhile our DC/OS integration here will provide TLS support.

2016-10-27 07:29 UTC, markusjura requested changes

2016-10-27 07:29 UTC, markusjura commented on conductr_cli/conduct_main.py
> +    args = parser.parse_args(_args[1:])
We are removing here always the first argument. Also in non DCOS mode. Does that makes sense?

2016-10-27 07:29 UTC, markusjura commented on conductr_cli/conduct_main.py
> +        if not vars(args).get('dcos_info'):
For readability reasons I'd would swap the if and else clause:

```
        if vars(args).get('dcos_info'):
            print('Lightbend ConductR sub commands. Type \'dcos conduct\' to see more.')
            exit(0)            
        else:
            parser.print_help()
```

2016-10-27 07:29 UTC, markusjura commented on conductr_cli/sandbox_run.py
> +            conduct_request.get(False, ConductArgs.ip, url, timeout=DEFAULT_HTTP_TIMEOUT)
Always specify the named argument when passing in a boolean:

```
conduct_request.get(dcos_mode=False, ConductArgs.ip, url, timeout=DEFAULT_HTTP_TIMEOUT)
```

2016-10-27 07:29 UTC, markusjura commented on conductr_cli/test/conduct_load_test_base.py
> +                                       headers={'Host': '127.0.0.1'})
Why is this change necessary?

2016-10-27 07:30 UTC, markusjura commented
> conduct init needs to create a soft link to the `conduct.py` file from `~/.dcos/subcommands/conductr/env/bin/dcos-conduct`

What do you mean by that? We only have a `sandbox init` command but this should not be involved in DCOS mode.

2016-10-27 07:35 UTC, huntc commented
> What do you mean by that? We only have a sandbox init command but this should not be involved in DCOS mode.

In order to make the DC/OS CLI aware of the ConductR CLI, you have to tell it. Ordinarily, this is done via `dcos install --cli <package>`, but we don't have a universal package available (yet). So, meanwhile then, `conduct init` will automatically set things up.

2016-10-27 07:38 UTC, huntc commented on conductr_cli/conduct_main.py
> +    args = parser.parse_args(_args[1:])
Yes. This is what the previous code was actually doing under the hood.

2016-10-27 07:38 UTC, huntc commented on conductr_cli/conduct_main.py
> +        if not vars(args).get('dcos_info'):
Why would that be more readable?

2016-10-27 07:40 UTC, huntc commented on conductr_cli/sandbox_run.py
> +            conduct_request.get(False, ConductArgs.ip, url, timeout=DEFAULT_HTTP_TIMEOUT)
ok, but I do then have to specify the other arg names.

2016-10-27 07:41 UTC, huntc commented on conductr_cli/test/conduct_load_test_base.py
> +                                       headers={'Host': '127.0.0.1'})
We were previously checking the host header being set up via another mock. The other mock was no longer available due to its function having been replaced. The code should also be much simpler now.

2016-10-27 07:44 UTC, markusjura commented on conductr_cli/conduct_main.py
> +        if not vars(args).get('dcos_info'):
We are saving a "not". In a if / else statement you should never start with the negative, but always with the positive case.

2016-10-27 07:45 UTC, markusjura commented on conductr_cli/sandbox_run.py
> +            conduct_request.get(False, ConductArgs.ip, url, timeout=DEFAULT_HTTP_TIMEOUT)
Your decision. Not critical.

2016-10-27 07:45 UTC, markusjura commented on conductr_cli/test/conduct_load_test_base.py
> +                                       headers={'Host': '127.0.0.1'})
👍

2016-10-27 07:47 UTC, markusjura approved these changes

2016-10-27 07:47 UTC, markusjura commented on conductr_cli/conduct_main.py
> +    args = parser.parse_args(_args[1:])
👍

2016-10-27 07:47 UTC, huntc commented on conductr_cli/conduct_main.py
> +        if not vars(args).get('dcos_info'):
There's also an argument to doc the happy path, but I'll go with it.

2016-10-28 23:44 UTC, huntc commented
Waiting on a new DCOS lib release. PR tests will fail here until the following PR is merged and there's a new release of the DCOS lib: https://github.com/dcos/dcos-cli/pull/823

2016-10-31 07:56 UTC, markusjura commented
Integration test with `http://dcos-master.lightbend.com` was successful.

2016-11-01 05:21 UTC, merged