implement `sandbox logs`
typesafehub/conductr-cli pull request #276
Opened 2017-01-25 17:20 UTC by longshorej

This adds a `sandbox logs` command that uses `tail` to view the latest core and agent logs and optionally follow them with the provided `-f` argument.

```
~/work/lightbend/conductr-cli#logs-cmd $ sandbox logs --help
usage: sandbox logs [-h] [--image-dir IMAGE_DIR] [-f] [-n LINES]

optional arguments:
  -h, --help            show this help message and exit
  --image-dir IMAGE_DIR
                        Default directory where sandbox images is stored.
  -f, --follow          Output appended as the log files grow
  -n LINES, --lines LINES
                        Output the last NUM lines (default 10)
-> 0

~/work/lightbend/conductr-cli#logs-cmd $ sandbox logs -n 2
2017-01-25T16:25:39Z meddle INFO  RemoteActorRefProvider$RemotingTerminator [sourceThread=conductr-akka.remote.default-remote-dispatcher-7, akkaSource=akka.tcp://conductr@192.168.10.1:9004/system/remoting-terminator, sourceActorSystem=conductr, akkaTimestamp=16:25:39.527UTC] - Remote daemon shut down; proceeding with flushing remote transports.
2017-01-25T16:25:39Z meddle INFO  RemoteActorRefProvider$RemotingTerminator [sourceThread=conductr-akka.remote.default-remote-dispatcher-15, akkaTimestamp=16:25:39.539UTC, akkaSource=akka.tcp://conductr@192.168.10.1:9004/system/remoting-terminator, sourceActorSystem=conductr] - Remoting shut down.
2017-01-25T16:25:39Z meddle INFO  Remoting [sourceThread=conductr-agent-akka.actor.default-dispatcher-4, akkaTimestamp=16:25:39.877UTC, akkaSource=akka.remote.Remoting, sourceActorSystem=conductr-agent] - Remoting shut down
2017-01-25T16:25:39Z meddle INFO  RemoteActorRefProvider$RemotingTerminator [sourceThread=conductr-agent-akka.remote.default-remote-dispatcher-8, akkaTimestamp=16:25:39.877UTC, akkaSource=akka.tcp://conductr-agent@192.168.10.1:2552/system/remoting-terminator, sourceActorSystem=conductr-agent] - Remoting shut down.
-> 0
```

2017-01-25 20:48 UTC, huntc requested changes
Just occurred to me that the logs command won't work on windoze. While we don't currently support the new sandbox for Windows, we may in the future. Wdyt?

Also there's a v1/v2 ConductR consideration here. May be we allow this command just for v2.

2017-01-25 20:59 UTC, longshorej commented
Yeah, it won't work on Windows. Neither will the newly added `sandbox ps` AFAIK. The way I see it is that we'd have a few options:

1. Require the use of [Windows Subsystem for Linux](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) on Windows
2. Rework any components in the CLI that rely on typical POSIX binaries to be present and implement the functionality using python and various libs instead.
3. Cygwin?

I'm partial to # 2 personally because I like portable code but certainly it is more work.

2017-01-25 21:31 UTC, huntc commented
Yeah #2 - that's the strategy we've had so far (forgot about sandbox ps - we need to fix that too).

2017-01-26 16:44 UTC, longshorej commented
We can use [psutil](http://pythonhosted.org/psutil/) to implement `sandbox ps` in a portable way. I'll work on that today.

`sandbox logs` can be implemented using python stdlib I/O calls. After `sandbox ps` is made portable I'll rebase this PR on those changes and update this PR making `sandbox logs` portable as well.

2017-01-26 18:39 UTC, huntc commented
Thanks!

2017-01-26 19:07 UTC, longshorej commented
I'll resubmit with a native implementation.

2017-01-26 19:07 UTC, closed without merging