WIP - DON'T MERGE - Sandbox run env sys props
typesafehub/conductr-cli pull request #302
Opened 2017-02-07 06:55 UTC by fsat

2017-02-13 06:05 UTC, fsat commented
Manual test is performed successfully.

**Scenario: custom args and envs**

Sandbox is started with custom args and envs.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ sandbox run 2.0.0 -f visualization \
>   --arg="-Dcommon.1=1" --arg="-Dcommon.2=2" \
>   --arg-core="-Dcore.1=1" --arg-core="-Dcore.2=2" \
>   --arg-agent="-Dagent.1=1" --arg-agent="-Dagent.2=2" \
>   --env="COMMON_1=1" --env="COMMON_2=1" \
>   --env-core="CORE_1=1" --env-core="CORE_2=1" \
>   --env-agent="AGENT_1=1" --env-agent="AGENT_2=1"
|------------------------------------------------|
| Starting ConductR                              |
|------------------------------------------------|
Extracting ConductR core to /Users/felixsatyaputra/.conductr/images/core
Extracting ConductR agent to /Users/felixsatyaputra/.conductr/images/agent
Starting ConductR core instance on 192.168.10.1..
Starting ConductR agent instance on 192.168.10.1..
Waiting for ConductR to start..
|------------------------------------------------|
| Starting logging feature based on eslite       |
|------------------------------------------------|
Deploying bundle eslite..
Retrieving bundle..
Loading bundle from cache typesafe/bundle/eslite
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving from cache /Users/felixsatyaputra/.conductr/cache/bundle/eslite-v1-c4acb219a37ce782222b94138987905f6c41be956b0cfe0156c96bdada7a596a.zip
Loading bundle to ConductR..
[#################################################] 100%
Bundle c4acb219a37ce782222b94138987905f is installed
Bundle loaded.
Bundle run request sent.
Bundle c4acb219a37ce782222b94138987905f waiting to reach expected scale 1
Bundle c4acb219a37ce782222b94138987905f has scale 0, expected 1..
Bundle c4acb219a37ce782222b94138987905f expected scale 1 is met
|------------------------------------------------|
| Starting visualization feature                 |
|------------------------------------------------|
Deploying bundle visualizer..
Retrieving bundle..
Loading bundle from cache typesafe/bundle/visualizer
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving from cache /Users/felixsatyaputra/.conductr/cache/bundle/visualizer-v2-13f9a3c35855b2f3a0f01d971c6b62012e5fe6f17da5f5e8d1d54a33ead7a300.zip
Loading bundle to ConductR..
[#################################################] 100%
Bundle 13f9a3c35855b2f3a0f01d971c6b6201 is installed
Bundle loaded.
Bundle run request sent.
Bundle 13f9a3c35855b2f3a0f01d971c6b6201 waiting to reach expected scale 1
Bundle 13f9a3c35855b2f3a0f01d971c6b6201 has scale 0, expected 1.
Bundle 13f9a3c35855b2f3a0f01d971c6b6201 expected scale 1 is met
|------------------------------------------------|
| Summary                                        |
|------------------------------------------------|
|- - - - - - - - - - - - - - - - - - - - - - - - |
| ConductR                                       |
|- - - - - - - - - - - - - - - - - - - - - - - - |
ConductR has been started:
  core instance on 192.168.10.1
  agent instance on 192.168.10.1
ConductR service locator has been started on:
  192.168.10.1:9008
|- - - - - - - - - - - - - - - - - - - - - - - - |
| Proxy                                          |
|- - - - - - - - - - - - - - - - - - - - - - - - |
HAProxy has not been started
To enable proxying ensure Docker is running and restart the sandbox
|- - - - - - - - - - - - - - - - - - - - - - - - |
| Features                                       |
|- - - - - - - - - - - - - - - - - - - - - - - - |
The following feature related bundles have been started:
  visualizer on 192.168.10.1:9008/services/visualizer
|- - - - - - - - - - - - - - - - - - - - - - - - |
| Bundles                                        |
|- - - - - - - - - - - - - - - - - - - - - - - - |
Check latest bundle status with:
  conduct info
Current bundle status:
ID       NAME        #REP  #STR  #RUN
c4acb21  eslite         1     0     1
13f9a3c  visualizer     1     0     1
```

Visualizer is confirmed to be working by accessing http://192.168.10.1:9008/services/visualizer

When inspecting Core process, the following system properties are specified: `-Dcommon.1=1 -Dcommon.2=2 -Dcore.1=1 -Dcore.2=2` and the following environments are specified `COMMON_1=1`, `COMMON_2=1`, `CORE_1=1`, and `CORE_2=1`.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ ps -wwE -p 88339
  PID TTY           TIME CMD
88339 ??         0:32.05 java -javaagent:/Users/felixsatyaputra/.conductr/images/core/bin/../cinnamon/cinnamon-agent-2.1.0.jar -Djava.library.path=/Users/felixsatyaputra/.conductr/images/core/lib/sigar -server -Xms210m -Xmx256m -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=/Users/felixsatyaputra/.conductr/images/tmp -Dakka.loglevel=info -Dconductr.ip=192.168.10.1 -Dconductr.resource-provider.match-offer-roles=off -Dcommon.1=1 -Dcommon.2=2 -Dcore.1=1 -Dcore.2=2 -Dcontrail.syslog.server.port=9200 -Dcontrail.syslog.server.elasticsearch.enabled=on -cp /Users/felixsatyaputra/.conductr/images/core/lib/com.typesafe.conductr.conductr-2.0.0.jar:/Users/felixsatyaputra/.conductr/images/core/lib/com.typesafe.conductr.conductr-common-2.0.0.jar:/Users/felixsatyaputra/.conductr/images/core/lib/org.scala-lang.scala-library-2.11.8.jar:/Users/felixsatyaputra/.conductr/images/core/lib/com.typesafe.akka.akka-actor_2.11-2.4.14.jar:/Users/felixsatyaputra/.conductr/images/core/lib/com.typesafe.config-1.3.0.jar:/Users/felixsatyaputra/.conductr/images/core/lib/org.scala-lang.modules.scala-java8-compat_2.11-0.7.0.jar:/Users/felixsatyaputra/.conductr/images/core/lib/com.typesafe.akka.akka-cluster-tools_2.11-2.4.14.jar:/Users/felixsatyaputra/.conductr/images/core/lib/com.typesafe.akka.akka-cluster_2.11-2.4.14.jar:/Users/felixsatyaputra/.conductr/images/core/lib/com.typesafe.akka.akka-remote_2.11-2.4.14.jar:/Users/felixsatyaputra/.conductr/images/core/lib/com.typesafe.akka.akka-stream_2.11-2.4.14.jar:/Users/felixsatyaputra/.conductr/images/core/lib/org.reactivestreams.reactive-streams-1.0.0.jar:/Users/felixsatyaputra/.conductr/images/core/lib/com.typesafe.ssl-config-core_2.11-0.2.1.jar:/Users/felixsatyaputra/.conductr/images/core/lib/org.scala-lang.modules.scala-parser-combinators_2.11-1.0.4.jar:/Users/felixsatyaputra/.conductr/images/core/lib/com.typesafe.akka.akka-protobuf_2.11-2.4.14.jar:/Users/felixsatyaputra/.conductr/images/core/lib/io.netty.netty-3.10.6.Final.jar:/Users/felixsatyaputra/.conductr/images/core/lib/org.uncommons.maths.uncommons-maths-1.2.2a.jar:/Users/felixsatyaputra/.conductr/images/core/lib/io.aeron.aeron-driver-1.0.4.jar:/Users/felixsatyaputra/.conductr/images/core/lib/io.aeron.aeron-client-1.0.4.jar:/Users/felixsatyaputra/.conductr/images/core/lib/org.agrona.Agrona-0.9.0.jar:/Users/felixsatyaputra/.conductr/images/core/lib/com.typesafe.akka.akka-http_2.11-10.0.0.jar:/Users/felixsatyaputra/.conductr/images/core/lib/com.typesafe.akka.akka-http-core_2.11-10.0.0.jar:/Users/felixsatyaputra/.conductr/images/core/lib/com.typesafe.akka.akka-parsing_2.11-10.0.0.jar:/Users/felixsatyaputra/.conductr/images/core/lib/org.apache.commons.commons-compress-1.11.jar:/Users/felixsatyaputra/.conductr/images/core/lib/commons-io.commons-io-2.5.jar:/Users/felixsatyaputra/.conductr/images/core/lib/org.apache.mesos.mesos-1.0.1.jar:/Users/felixsatyaputra/.conductr/images/core/lib/com.google.protobuf.protobuf-java-2.6.1.jar:/Users/felixsatyaputra/.conductr/images/core/lib/io.spray.spray-caching_2.11-1.3.3.jar:/Users/felixsatyaputra/.conductr/images/core/lib/io.spray.spray-util_2.11-1.3.3.jar:/Users/felixsatyaputra/.conductr/images/core/lib/com.googlecode.concurrentlinkedhashmap.concurrentlinkedhashmap-lru-1.4.2.jar:/Users/felixsatyaputra/.conductr/images/core/lib/com.lightbend.akka.akka-split-brain-resolver_2.11-1.0.0.jar:/Users/felixsatyaputra/.conductr/images/core/lib/com.lightbend.akka.akka-diagnostics_2.11-1.0.0.jar:/Users/felixsatyaputra/.conductr/images/core/lib/com.typesafe.akka.akka-contrib-extra_2.11-3.3.2.jar:/Users/felix [...]

2017-02-13 08:03 UTC, markusjura requested changes

2017-02-13 08:03 UTC, markusjura commented on conductr_cli/sandbox_main.py
>                              help='Set additional environment variables for each ConductR container\n'
Can you change the description to:

```
Set additional environment variables for each ConductR core and agent process.\n 
Defaults to [].
```

2017-02-13 08:03 UTC, markusjura commented on conductr_cli/sandbox_main.py
> +                            help='Set additional environment variables for each ConductR core process. Defaults to [].',
`Defaults to` is always on a separate line. Also, we don't use dots at the end of the line.

So it should be changed to:

```
Set additional environment variables for each ConductR core process\n
Defaults to []
```

2017-02-13 08:03 UTC, markusjura commented on conductr_cli/sandbox_main.py
> +                            help='Set additional environment variables for each ConductR agent process. Defaults to [].',
`Defaults to` is always on a separate line. Also, we don't use dots at the end of the line.

So it should be changed to:

```
Set additional environment variables for each ConductR agent process\n
Defaults to []
```

2017-02-14 00:11 UTC, fsat commented on conductr_cli/sandbox_main.py
>                              help='Set additional environment variables for each ConductR container\n'
Description updated.

2017-02-14 00:11 UTC, fsat commented on conductr_cli/sandbox_main.py
> +                            help='Set additional environment variables for each ConductR core process. Defaults to [].',
Description updated.

2017-02-14 00:12 UTC, fsat commented on conductr_cli/sandbox_main.py
> +                            help='Set additional environment variables for each ConductR agent process. Defaults to [].',
Description updated.

2017-02-14 02:34 UTC, huntc approved these changes
Just one question

2017-02-14 02:34 UTC, huntc commented on conductr_cli/sandbox_proxy.py
> +DEFAULT_PROXY_PORTS = [80, 443]  # These are the ports which will be opened by default to the proxy.
Why was 9000 removed?

2017-02-14 10:15 UTC, fsat commented on conductr_cli/sandbox_proxy.py
> +DEFAULT_PROXY_PORTS = [80, 443]  # These are the ports which will be opened by default to the proxy.
This is remove in lieu of the existing `--bundle-http-port` default argument:

https://github.com/typesafehub/conductr-cli/pull/302/files#diff-6089c6531dbfde85064554aba3e7de40R153

So the value supplied by `--bundle-http-port` is passed into the `sandbox_proxy` to be exposed when starting the docker container.

2017-02-14 10:17 UTC, markusjura approved these changes

2017-02-14 22:56 UTC, merged