WIP - DON'T MERGE - Download license from Lightbend.com as part of load-license command
typesafehub/conductr-cli pull request #345
Opened 2017-03-14 04:45 UTC by fsat

2017-03-14 06:17 UTC, fsat commented
![](https://github.trello.services/images/mini-trello-icon.png) [Extend the CLI with a load-license sub command](https://trello.com/c/FIVSGR8O/549-extend-the-cli-with-a-load-license-sub-command)

2017-03-15 01:05 UTC, fsat commented
**Manual test setup**

Create a stub license endpoint to be run locally as such:

```
package stublicense

import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.http.scaladsl.model.HttpResponse
import akka.http.scaladsl.server.directives.Credentials
import akka.stream.ActorMaterializer
import akka.http.scaladsl.server.Directives._

import scala.concurrent.Await
import scala.concurrent.duration._

object Main {
  private def start(): Unit = {
    implicit val system = ActorSystem("test-server")
    implicit val mat = ActorMaterializer()
    import system.dispatcher

    val license =
      """
        |===== LIGHTBEND PRODUCTION SUITE LICENSE =====
        |
        |DO NOT TAMPER WITH THIS FILE - DOING SO CONTRAVENES THE LICENSE YOU’VE AGREED TO:
        |http://downloads.lightbend.com/website/legal/LightbendSubscriptionAgreement.pdf
        |
        |user: cc64df31-ec6b-4e08-bb6b-3216721a56b@lightbend
        |conductr-versions: 2.1.*
        |max-conductr-agents: 3
        |grants: conductr, cinnamon, akka-sbr
        |expiry: 2018-03-01T00:00:00Z
        |
        |------------------------------------------------------------
        |AAAAAQAAAKV1c2VyOiBjYzY0ZGYzMS1lYzZiLTRlMDgtYmI2Yi0zMjE2NzIx
        |YTU2YkBsaWdodGJlbmQKY29uZHVjdHItdmVyc2lvbnM6IDIuMS4qCm1heC1j
        |b25kdWN0ci1hZ2VudHM6IDMKZ3JhbnRzOiBjb25kdWN0ciwgY2lubmFtb24s
        |IGFra2Etc2JyCmV4cGlyeTogMjAxOC0wMy0wMVQwMDowMDowMFoAAAAuMCwC
        |FBOFk7pJ9SKHY2v1Q1c10Y6JEjqAAhQ1hgiR2D91kUTVShGPHafP0p3k5w==
        |------------------------------------------------------------
      """.stripMargin

    val oauth2TokenValidator: Authenticator[String] = {
      case u @ Credentials.Provided(token) if u.verify("valid-token") =>
        Some(token)
      case u @ Credentials.Provided(token) if u.verify("no-terms-token") =>
        Some(token)
      case u @ Credentials.Provided(token) if u.verify("expired-token") =>
        Some(token)
      case _ => None
    }

    val route =
      pathPrefix("product" / "conductr" / "license") {
        pathEndOrSingleSlash {
          get {
            authenticateOAuth2(realm = "Lightbend.com", oauth2TokenValidator) { token =>
              if (token == "valid-token") {
                complete(license)
              } else if (token == "no-terms-token") {
                complete(
                  HttpResponse(
                    403,
                    entity = "Please accept our terms and conditions first. Please visit https://www.lightbend.com/account/access-token to accept them."
                  )
                )
              } else {
                complete(
                  HttpResponse(
                    401,
                    entity = "Your credentials are no longer valid. Please visit https://www.lightbend.com/account/access-token to renew them."
                  )
                )
              }


            }
          }
        }
      }

    println("Starting HTTP listener...")
    val server = Http(system).bindAndHandle(route, "0.0.0.0", 7777)
    Await.ready(server, 10.seconds)
    println("HTTP listener started")
  }

  def main(args: Array[String]): Unit = {
    System.setProperty("akka.log-dead-letters", "false")
    System.setProperty("akka.log-dead-letters-during-shutdown", "false")
    System.setProperty("akka.http.parsing.max-content-length", "200m")

    println("Starting stub license...")
    start()
  }
}

```

2017-03-15 02:07 UTC, fsat commented
**Manual test**

Start the sandbox without license.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ sandbox run 2.1.0-SNAPSHOT
|------------------------------------------------|
| Starting ConductR                              |
|------------------------------------------------|
Extracting ConductR core to /Users/felixsatyaputra/.conductr/images/core
Extracting ConductR agent to /Users/felixsatyaputra/.conductr/images/agent
Starting ConductR core instance on 192.168.10.1..
Starting ConductR agent instance on 192.168.10.1..
Waiting for ConductR to start.
|------------------------------------------------|
| Starting proxying feature                      |
|------------------------------------------------|
HAProxy has not been started
To enable proxying ensure Docker is running and restart the sandbox
|------------------------------------------------|
| Starting logging feature based on eslite       |
|------------------------------------------------|
Deploying bundle eslite..
Retrieving bundle..
Loading bundle from cache typesafe/bundle/eslite
Bintray credentials loaded from /Users/felixsatyaputra/.lightbend/commercial.credentials
Retrieving from cache /Users/felixsatyaputra/.conductr/cache/bundle/eslite-v1-3349b6bfbc09e8d88123fee5b33b2717e07fb2a91de719c99e0403c9e4b28ea5.zip
Loading bundle to ConductR..
[#################################################] 100%
Bundle 3349b6bfbc09e8d88123fee5b33b2717 is installed
Bundle loaded.
Bundle run request sent.
Bundle 3349b6bfbc09e8d88123fee5b33b2717 waiting to reach expected scale 1
Bundle 3349b6bfbc09e8d88123fee5b33b2717 has scale 0, expected 1..
Bundle 3349b6bfbc09e8d88123fee5b33b2717 expected scale 1 is met
|------------------------------------------------|
| Summary                                        |
|------------------------------------------------|
|- - - - - - - - - - - - - - - - - - - - - - - - |
| ConductR                                       |
|- - - - - - - - - - - - - - - - - - - - - - - - |
ConductR has been started:
  core instance on 192.168.10.1
  agent instance on 192.168.10.1
ConductR service locator has been started on:
  192.168.10.1:9008
|- - - - - - - - - - - - - - - - - - - - - - - - |
| Bundles                                        |
|- - - - - - - - - - - - - - - - - - - - - - - - |
Check latest bundle status with:
  conduct info
Current bundle status:
UNLICENSED - please use "conduct load-license" to use more agents. Additional agents are freely available for registered users.
Licensed To: unknown
Max ConductR agents: 1
ConductR Version(s): 2.1.*
Grants: akka-sbr, cinnamon, conductr

ID       NAME    #REP  #STR  #RUN
3349b6b  eslite     1     0     1
```

**Success test case without cached token**

Download the license using `conduct load-license`.

As this is the first time the command is run, there are no cached auth token. The token prompt is presented (i.e. `Enter Access Token:` prompt).

Once a valid token is entered, the license is loaded. This is verified by `conduct info` command.

The token is now cached in `~/.lightbend/auth-token`.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ ll ~/.lightbend/auth-token
ls: /Users/felixsatyaputra/.lightbend/auth-token: No such file or directory

Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct load-license --license-download-url http://localhost:7777/product/conductr/license
Credentials are required. Please visit https://www.lightbend.com/account/access-token to obtain credentials, and a free license or your commercial one.

Enter Access Token: valid-token
Loading license into ConductR at 192.168.10.1

Licensed To: cc64df31-ec6b-4e08-bb6b-3216721a56b@lightbend
Max ConductR agents: 3
Expires In: 350 days (Thu 01 Mar 2018 11:00AM)
ConductR Version(s): 2.1.*
Grants: akka-sbr, cinnamon, conductr

License successfully loaded

Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct info
Licensed To: cc64df31-ec6b-4e08-bb6b-3216721a56b@lightbend
Max ConductR agents: 3
Expires In: 350 days (Thu 01 Mar 2018 11:00AM)
ConductR Version(s): 2.1.*
Grants: akka-sbr, cinnamon, conductr

ID       NAME    #REP  #STR  #RUN
3349b6b  eslite     1     0     1

Felixs-MBP-2:conductr-cli felixsatyaputra$ cat ~/.lightbend/auth-token
valid-token
```

**Success test case with cached token**

Restart the sandbox with the same command. Re-run `conduct load license`. Cached token is used this time, and user is not prompted for access token.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ cat ~/.lightbend/auth-token
valid-token

Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct load-license --license-download-url http://localhost:7777/product/conductr/license
Loading license into ConductR at 192.168.10.1

Licensed To: cc64df31-ec6b-4e08-bb6b-3216721a56b@lightbend
Max ConductR agents: 3
Expires In: 350 days (Thu 01 Mar 2018 11:00AM)
ConductR Version(s): 2.1.*
Grants: akka-sbr, cinnamon, conductr

License successfully loaded

Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct info
Licensed To: cc64df31-ec6b-4e08-bb6b-3216721a56b@lightbend
Max ConductR agents: 3
Expires In: 350 days (Thu 01 Mar 2018 11:00AM)
ConductR Version(s): 2.1.*
Grants: akka-sbr, cinnamon, conductr

ID       NAME    #REP  #STR  #RUN
3349b6b  eslite     1     0     1
```

**Expired cached token**

When cached token has expired, error message from response text will be displayed and cached token will be deleted. Re-running `conduct load-license` afterwards will produce a prompt for a new access token.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ cat ~/.lightbend/auth-token
expired-token

Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct load-license --license-download-url http://localhost:7777/product/conductr/license
Error: Your credentials are no longer valid. Please visit https://www.lightbend.com/account/access-token to renew them.

Felixs-MBP-2:conductr-cli felixsatyaputra$ ll ~/.lightbend/auth-token
ls: /Users/felixsatyaputra/.lightbend/auth-token: No such file or directory

Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct load-license --license-download-url http://localhost:7777/product/conductr/license
Credentials are required. Please visit https://www.lightbend.com/account/access-token to obtain credentials, and a free license or your commercial one.

Enter Access Token:
```

**Expired token is entered**

If expired token is entered, the error message from the response text (prepared by stub in this case) is displayed. The expired token won't be cached.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct load-license --license-download-url http://localhost:7777/product/conductr/license
Credentials are required. Please visit https://www.lightbend.com/account/access-token to obtain credentials, and a free license or your commercial one.

Enter Access Token: expired-token
Error: Your credentials are no longer valid. Please visit https://www.lightbend.com/account/access-token to renew them.

Felixs-MBP-2:conductr-cli felixsatyaputra$ ll ~/.lightbend/auth-token
ls: /Users/felixsatyaputra/.lightbend/auth-token: No such file or directory
```


**User has not accepted t&c**

If user has not accepted t&c (i.e. HTTP `403` is returned), the  error message from the response text (prepared by stub in this case) is displayed. The token won't be cached.

```
Felixs-MBP-2:conductr-cli felixsatyaputra$ conduct load-license --license-download-url http://localhost:7777/product/conductr/license
Credentials are required. Please visit https://www.lightbend.com/account/access-token to obtain credentials, and a free license or your commercial one.

Enter Access Token: no-terms-token
Error: Please accept our terms and conditions first. Please visit https://www.lightbend.com/account/access-token to accept them.

Felixs-MBP-2:conductr-cli felixsatyaputra$ ll ~/.lightbend/auth-token
ls: /Users/felixsatyaputra/.lightbend/auth-token: No such file or directory
```

2017-03-15 22:39 UTC, huntc requested changes

2017-03-15 22:39 UTC, huntc commented on conductr_cli/license.py
> +    auth_header = {'Authorization': 'Bearer {}'.format(auth_token)}
Note that the `auth-token` requires encoding to Base64 as per OAuth spec.

2017-03-15 22:39 UTC, huntc commented on conductr_cli/license_auth.py
> +                    'Enter Access Token: '
I realise that this was in the SD, but how about:

```
+AUTH_TOKEN_PROMPT = 'An access token is required. Please visit https://www.lightbend.com/account/access-token to obtain ' \
                    'your access token, and a free license or your commercial one.\n' \
                    '\n' \
                    'Please enter your access token: '
```

2017-03-15 23:15 UTC, fsat commented on conductr_cli/license.py
> +    auth_header = {'Authorization': 'Bearer {}'.format(auth_token)}
Thanks for catching this - I missed this one!

2017-03-15 23:23 UTC, longshorej reviewed
Looks good to me! +1 on Christopher's tweak to wording regarding Credentials vs access token.

2017-03-15 23:33 UTC, fsat commented
Marked as wip while addressing PR feedback. I'd like to redo the manual test as well.

2017-03-15 23:33 UTC, fsat commented
Thanks @longshorej !

2017-03-15 23:56 UTC, fsat commented on conductr_cli/license_auth.py
> +                    'Enter Access Token: '
Text is now updated

2017-03-15 23:57 UTC, fsat commented on conductr_cli/license.py
> +    auth_header = {'Authorization': 'Bearer {}'.format(auth_token)}
This is now Base64 encoded.

2017-03-16 00:01 UTC, fsat commented
Manual test scenario is repeated with the same, successful result after PR feedback changes.

2017-03-16 00:05 UTC, fsat commented
PR feedback squashed.

2017-03-16 00:06 UTC, huntc approved these changes

2017-03-16 00:07 UTC, merged