Hostname lookup validation pre-check
typesafehub/conductr-cli pull request #372
Opened 2017-03-27 12:25 UTC by markusjura

Adding additional check that the hostname lookup doesn’t take too long. This validation is necessary to check if ConductR would fail at startup given this issue with Java 8 on macOS: https://github.com/akka/akka/issues/22160

The validation is failing if the hostname is not part of the `/etc/hosts` file and if the operation system is macOS. In this case, we abort with this error:

```
$ sandbox run 2.0.2
Error: Hostname lookup took 5006 milliseconds which will result in a ConductR startup failure
Error: This is known Java 8 issue on macOS: http://stackoverflow.com/questions/39636792/jvm-takes-a-long-time-to-resolve-ip-address-for-localhost
Error: To speed up the hostname lookup add your macOS hostname to /etc/hosts
Error: Resolves your hostname on the terminal with: hostname
Error: Sample /etc/hosts file:
Error: 127.0.0.1   localhost mbpro.local
Error: ::1         localhost mbpro.local
```

We do not check for the Java version given that this error only occurs from Java 8 onwards and ConductR supports only Java 8 and onwards.

The check is only performed in sandbox JVM mode.

2017-03-27 19:52 UTC, huntc requested changes

2017-03-27 19:52 UTC, huntc commented on conductr_cli/sandbox_run_jvm.py
> +    if host.is_macos():
I do think we should check the Java version also as the CLI can operate on a machine where non ConductR dev occurs.

2017-03-27 19:52 UTC, huntc commented on conductr_cli/validation.py
> +            log.error('This is known Java 8 issue on macOS: http://stackoverflow.com/questions/39636792/'
"Mac OS X"

2017-03-27 21:36 UTC, longshorej commented on conductr_cli/validation.py
> +            log.error('This is known Java 8 issue on macOS: http://stackoverflow.com/questions/39636792/'
Isn't it "macOS" now? http://www.apple.com/macos/sierra/

2017-03-27 21:49 UTC, huntc commented on conductr_cli/validation.py
> +            log.error('This is known Java 8 issue on macOS: http://stackoverflow.com/questions/39636792/'
I'm starting to feel old now. You both win. :-)

2017-03-28 05:54 UTC, markusjura commented on conductr_cli/validation.py
> +            log.error('This is known Java 8 issue on macOS: http://stackoverflow.com/questions/39636792/'
Yes, we also using `macOS` in every other place.

2017-03-28 05:55 UTC, markusjura commented on conductr_cli/sandbox_run_jvm.py
> +    if host.is_macos():
We validate the Java version prior to this check. So if the Java version is not valid then we do not we will abort before we perform the hostname lookup validation.

2017-03-28 05:56 UTC, huntc approved these changes

2017-03-28 05:56 UTC, merged