Encapsulating ConductR version validation
typesafehub/conductr-cli pull request #379
Opened 2017-03-29 12:29 UTC by markusjura

Based on a given ConductR version, the `sandbox run` command performed certain validations, e.g. run ConductR in JVM or Docker mode, run certain features, check Bintray credentials, etc.

So far each version check was directly made in the corresponding function. With this PR, we enscapsulate the version checks to a python module `sandbox_version`. This module offers functions to check for certain capabilities, e.g. `is_docker_mode`, `check_bintray_credentials`. Each function will return either True or False based on the given ConductR version.

Manual tests that cover all the different scenarios have been performed.

2017-03-29 14:12 UTC, longshorej approved these changes
Looks nice - good cleanup!

2017-03-29 14:12 UTC, longshorej commented on conductr_cli/sandbox_features.py
> +                                         parse_offline_mode_arg(self.offline_mode)
Looks like `tox` doesn't like the indent here.

2017-03-29 14:12 UTC, longshorej commented on conductr_cli/sandbox_features.py
> +                                  parse_offline_mode_arg(self.offline_mode)
nor here

2017-03-30 04:13 UTC, huntc commented on conductr_cli/sandbox_version.py
> +def is_docker_mode(version):
`is_sandbox_docker_based`

2017-03-30 04:16 UTC, huntc requested changes
Looking great!

2017-03-30 04:16 UTC, huntc commented on conductr_cli/sandbox_version.py
> +def is_docker_mode(version):
`is_sandbox_docker_based`

2017-03-30 04:16 UTC, huntc commented on conductr_cli/sandbox_version.py
> +def check_bintray_credentials(version):
`is_conductr_on_private_bintray`

2017-03-30 04:16 UTC, huntc commented on conductr_cli/sandbox_version.py
> +def with_features(version):
`is_conductr_supportive_of_features`

2017-03-30 13:47 UTC, merged