WIP - DO NOT MERGE - `conduct logs -f` implementation
typesafehub/conductr-cli pull request #428
Opened 2017-04-20 20:15 UTC by longshorej

- [X] diff function to determine new logs
- [ ] implement `-f` to use new diff function

2017-04-24 20:51 UTC, longshorej commented
![](https://github.trello.services/images/mini-trello-icon.png) [conductr-cli: Introduce tail behaviour to conduct logs](https://trello.com/c/S2KrHMRh/460-conductr-cli-introduce-tail-behaviour-to-conduct-logs)

2017-04-24 21:46 UTC, longshorej commented
Note: This mimics `tail -F` in behavior; that is, errors do not cause the program to exit. `conduct logs -f` will keep attempting to print logs of the bundle it is following.

### Manual Tests
-------------------------
*For `eslite` these tests depend on https://github.com/typesafehub/conductr/pull/1752*

Given a sandbox with logging enabled, load the visualizer. In one terminal, run `conduct logs -f visualizer`.

In another terminal, repeatedly start and stop the visualizer. Observe that logs are printed when the visualizer starts and stops. Unload the visualizer. Observe that the program continues to follow log data but prints an error. Load visualizer again and note that errors stop, and log stream is working again. Finally, `CTRL-C` to exit the program.

```bash
 
$ conduct logs -f visualizer
Mon 2017-04-24T16:39:47-0500 meddle [warn] application - application.conf @ file:/home/longshorej/.conductr/images/tmp/conductr-agent/192.168.10.1/bundles/6cc7dbcf3b655b1942edf50a5574d62f/execution-0-7787204643165569875/6cc7dbcf3b655b1942edf50a5574d62f5bbb12ef37db5b3990dc3fa80078b827/visualizer/conf/application.conf: 13: application.secret is deprecated, use play.crypto.secret instead
Mon 2017-04-24T16:39:47-0500 meddle [info] play.api.Play - Application started (Prod)
Mon 2017-04-24T16:39:47-0500 meddle [info] application - Signalled start to ConductR
Mon 2017-04-24T16:39:47-0500 meddle [info] p.c.s.NettyServer - Listening for HTTP on /192.168.10.1:10917
Mon 2017-04-24T16:41:52-0500 meddle Component visualizer exited with 143
Mon 2017-04-24T16:41:52-0500 meddle Stopping bundle
Mon 2017-04-24T16:42:17-0500 meddle [warn] application - application.conf @ file:/home/longshorej/.conductr/images/tmp/conductr-agent/192.168.10.1/bundles/6cc7dbcf3b655b1942edf50a5574d62f/execution-0-6936888153024354278/6cc7dbcf3b655b1942edf50a5574d62f5bbb12ef37db5b3990dc3fa80078b827/visualizer/conf/application.conf: 13: application.secret is deprecated, use play.crypto.secret instead
Mon 2017-04-24T16:42:17-0500 meddle [info] play.api.Play - Application started (Prod)
Mon 2017-04-24T16:42:17-0500 meddle [info] application - Signalled start to ConductR
Mon 2017-04-24T16:42:17-0500 meddle [info] p.c.s.NettyServer - Listening for HTTP on /192.168.10.1:10917
Mon 2017-04-24T16:45:17-0500 meddle Component visualizer exited with 143
Mon 2017-04-24T16:45:17-0500 meddle Stopping bundle
Mon 2017-04-24T16:45:27-0500 meddle [warn] application - application.conf @ file:/home/longshorej/.conductr/images/tmp/conductr-agent/192.168.10.1/bundles/6cc7dbcf3b655b1942edf50a5574d62f/execution-0-8913050399265601308/6cc7dbcf3b655b1942edf50a5574d62f5bbb12ef37db5b3990dc3fa80078b827/visualizer/conf/application.conf: 13: application.secret is deprecated, use play.crypto.secret instead
Mon 2017-04-24T16:45:27-0500 meddle [info] play.api.Play - Application started (Prod)
Mon 2017-04-24T16:45:27-0500 meddle [info] application - Signalled start to ConductR
Mon 2017-04-24T16:45:27-0500 meddle [info] p.c.s.NettyServer - Listening for HTTP on /192.168.10.1:10917
Mon 2017-04-24T16:45:31-0500 meddle Component visualizer exited with 143
Mon 2017-04-24T16:45:31-0500 meddle Stopping bundle
Error: 404 Not Found
Error: No bundle found by the specified Bundle ID/name: 'visualizer'
Mon 2017-04-24T16:45:52-0500 meddle [warn] application - application.conf @ file:/home/longshorej/.conductr/images/tmp/conductr-agent/192.168.10.1/bundles/6cc7dbcf3b655b1942edf50a5574d62f/execution-0-1710269803838206090/6cc7dbcf3b655b1942edf50a5574d62f5bbb12ef37db5b3990dc3fa80078b827/visualizer/conf/application.conf: 13: application.secret is deprecated, use play.crypto.secret instead
Mon 2017-04-24T16:45:52-0500 meddle [info] play.api.Play - Application started (Prod)
Mon 2017-04-24T16:45:52-0500 meddle [info] application - Signalled start to ConductR
Mon 2017-04-24T16:45:53-0500 meddle [info] p.c.s.NettyServer - Listening for HTTP on /192.168.10.1:10917
Mon 2017-04-24T16:46:07-0500 meddle Component visualizer exited with 143
Mon 2017-04-24T16:46:07-0500 meddle Stopping bundle
^C-> 0
```

2017-04-25 06:17 UTC, markusjura requested changes
Looking good. Two minor comments.

2017-04-25 06:17 UTC, markusjura commented on conductr_cli/conduct_logs.py
> +    return (new, len(old) > 0 and len(new) > 0) if answer is None else answer
I'd revert the if / else statement. If something is potentially `None` then we should check with `if answer` if it is not None:

```
return answer if answer else (new, len(old) > 0 and len(new) > 0)
```

2017-04-25 06:17 UTC, markusjura commented on conductr_cli/conduct_logs.py
> +        while not follow_is_done():
`follow_is_done()` currently always returns `False`:

```
ef follow_is_done():
    return False
```

This can't be right?!

2017-04-25 13:31 UTC, longshorej commented on conductr_cli/conduct_logs.py
> +    return (new, len(old) > 0 and len(new) > 0) if answer is None else answer
I simplified this - we just return `answer` now.

2017-04-25 13:31 UTC, longshorej commented on conductr_cli/conduct_logs.py
> +        while not follow_is_done():
This is a hook for testing - one of the tests has it return false after four executions.

2017-04-25 13:34 UTC, markusjura commented on conductr_cli/conduct_logs.py
> +        while not follow_is_done():
Can we somehow simulate a `CTRL + C` in the test?

2017-04-25 13:35 UTC, markusjura approved these changes

2017-04-25 14:02 UTC, merged